version: '2'
services:
    frontend:
        image: node:8
        volumes:
            - .:/react
            - /react/node_modules
        ports:
            - "3000:3000"
        working_dir: /react
        entrypoint: yarn start
